[profile.default]
src = './contracts'
out = './out'
libs = ['./lib']
test = './test'

optimizer = true
optimizer_runs = 200
evm_version = 'london'

[fmt]
line_length = 120
tab_width = 4
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@aave/=lib/protocol-v2/contracts/",
    "@uniswap/v2-periphery/=lib/v2-periphery/contracts/"
]